### PR TITLE
Stay In Touch - Milestone-6

### PR DESCRIPTION
**Pull request by Rhelli**
> This PR is for Microverse TSE review

# ☝🏽 Stay In Touch - Milestone 6
Hi there, 

This PR should contain the required features asked for milestone 6. They were previously implemented in milestone 5 (accidentally), hence there not being a lengthy commit history for this branch.

If you have any questions, please do get in contact with me via Slack or **@** me on Github.

All the best,

Rory

### CODE REVIEW

**Comment by Rhelli** [comment]
> This PR is for Microverse TSE review

# Stay In Touch ☝🏽 - Update # 1 
Following the code review and suggestions left by @euqueme, I have made some changes to this project so that it may more tightly fit the project spec as per the pathwright. The changes made are as following:

### Duplicate Friend Reuqest Issues
 - Validation created (':not_inviting_self') to prevent the user from creating a friendship where the current_user id is the sender id (user_id)
 - Callback method ':prevent_duplicates' created to avoid the scenario where the user1 can sends a friend request to user2, however, user2 can then send a friend request to user1, resulting in two unconfirmed friendships. As long as the reciever of a friend request has that friend request from the sender, they cannot send a friend request back to the reciever.
 - An additional callback conditional method '':inverse_exists?' has been created to remove the bar to creating a duplicate (in this case, inverse) friendship when the receiver of a friend request accepts. 

### Timeline & Posts
 - The posts index/timeline now only shows the users posts or friends of the user's posts
 - Testing has been updated to reflect these changes

****

If there are any other changes that are due to this project, feel free to reach out to me on Slack or @ me on Github!

Thanks,

Rory

**Comment by uryelah** [comment]
Hi **Rory Hellier**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with with the improvements! You are just missing one of the items mentioned before by the first reviewer.

# Required Changes 🏗️ 🐛 💡
 
- [ ] As mentioned by the previous TSE, there should be no view logic in the views, it should be in the helpers. 
View logic includes loops, `<% friends.each do ...` and conditionals `<% if condition...`, please refactor the logic in your views into helpers.


-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Rhelli** [comment]
> This PR is for Microverse TSE review

# Stay In Touch ☝🏽 - Update # 2
Hi there,

Stupidly I forgot to remove the logic from the views as suggested previously, but I have gone ahead and done that now. There should no longer be any if/else conditionals or loop calls in any of the views. 

Thanks,

Rory

**Comment by Rhelli** [comment]
@euqueme @uryelah Thanks for the code reviews and kind words! 🦾 🤟🏽

**Pull request merged**
